app/Http/routes.php
<?php
Route::get('/logout', [
    'as' => 'logout',
    'uses' => 'Auth\AuthController@getLogout'
]);

Route::get('/', [
    'as' => 'login',
    'uses' => 'Auth\AuthController@getLogin'
]);

Route::post('/', [
    'uses' => 'Auth\AuthController@postLogin'
]);

Route::group(['middleware' => 'auth'], function() {
    
    Route::model('projects', 'Project');

    Route::bind('projects', function($value) {
        return App\Project::whereSlug($value)->first();
    });

    Route::resource('projects', 'ProjectsController');
    Route::resource('tasks', 'TasksController');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{

    /**
     * sluggable columns
     * 
     * @var array 
     */
    public $sluggable = ['name'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'slug'];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::saving(function($model) {

            if (is_null($model->slug) && isset($model->sluggable)) {

                $sluggable = array_map(function($field) use ($model) {
                    return $model->$field;
                }, $model->sluggable);

                $model->attributes['slug'] = str_slug(join('-', $sluggable));
            }
        });
    }

    /**
     * Get the tasks for the project.
     */
    public function tasks()
    {
        return $this->hasMany(Task::class);
    }

    /**
     * add taks to project
     * 
     * @param \App\Task $task
     * @return type
     */
    public function addTask(Task $task)
    {
        return $this->tasks()->save($task);
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\EditProjectRequest;
use App\Project;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use function dd;
use function view;

class ProjectsController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('projects.index')->withProjects(Project::paginate(20));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  Project  $project
     * @return Response
     */
    public function show(Project $project)
    {
        return view('projects.show')->withProject($project);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Project $project
     * @return Response
     */
    public function edit(Project $project)
    {
        return view('projects.edit')->withProject($project);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  Project $project
     * @return Response
     */
    public function update(EditProjectRequest $request, Project $project)
    {
        $project->fill($request->all());
        $project->save();

        flash()->success('project updated', $project->name);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Project $project
     * @return Response
     */
    public function destroy(Project $project)
    {
        $project->delete();

        flash()->success('project deleted', $project->name);

        return redirect()->back();
    }
}

resources/views/projects/edit.blade.php
@extends('layout')

@section('body')
<div class="col-md-8">
    {!! Form::model($project, ['route' => ['projects.update', $project->slug], 'method' => 'PUT']) !!}
    @include ('projects.partials.form')

    <div class="btn-group" role="group">
        <a href="{{ route('projects.index') }}" class="btn btn-primary btn-info">{{ trans('back')}}</a>
        {!! Form::submit('save', ['class'=>'btn btn-primary btn-success']) !!}
    </div>
    {!! Form::close() !!}
</div>
@stop

resources/views/projects/index.blade.php
@extends('layout')

@section('body')
@if($projects)
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Slug</th>
            <th colspan='2'>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach($projects as $project)
        <tr>
            <td>
                {{ $project->id }}
            </td>
            <td>
                <a href="{{ url('projects', $project->slug) }}">
                    {{ $project->name }}
                </a>
            </td>
            <td>
                {{ $project->slug }}
            </td>
            <td>
                <a href="{{ route('projects.edit', $project->slug) }}" class="btn btn-primary btn-info">{{ trans('edit')}}</a>
            </td>
            <td>
                {!! Form::open(['url' => route('projects.destroy', $project->slug), 'method'=>'delete']) !!}
                <button type="submit" class="btn btn-danger">
                    &times;
                </button>
                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif
@stop

resources/views/projects/show.blade.php
@extends('layout')

@section('style')
<style>
    .task-completed {
        text-decoration: line-through;
    }
</style>
@stop

@section('body')
<div class="col-md-8">
    <div class="pull-right add-bottom">
        <a href="{{ route('projects.edit', $project->slug)}}" class="btn btn-info">
            edit
        </a>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>
                Project
            </th>
            <td>
                {{ $project->name }} 
            </td>
        </tr>
        <tr>
            <th>Tasks</th>
            <td>
                {!! Form::open([ 'url' => route('tasks.store')]) !!}
                <div class="form-group">
                    <label for="newTask">New Task</label>
                    <input id="newTask" name="name" value="" required="" class="form-control">
                    <input type="hidden" name="project_id" value="{{ $project->id }}">
                    <button type="submit" data-new-task class="btn btn-primary btn-success">add</button>
                </div>
                {!! Form::close() !!}
                <hr>
                @if ($project->tasks)  
                <ol data-tasks>
                    @foreach ($project->tasks as $task)
                    <li>
                        <label @if($task->completed)class="task-completed" @endif>
                                <input type="checkbox" data-complete-task="{{$task->id}}" @if($task->completed) checked=checked @endif>
                               {{$task->name}}
                        </label>
                    </li>
                    @endforeach   
                </ol>
                @else
                You have no task in current project, create one
                @endif
            </td>
        </tr>
    </table> 
</div>
@stop

@section('scripts')
<script>
    $(function () {

        var $list = $('[data-tasks]');
        $('[data-new-task]').on('click', function (e) {
            e.preventDefault();
            e.stopPropagation();
            var $form = $(this).closest('form');
            var $that = $(this);
            $.ajax({
                type: "POST",
                url: $form.attr('action'),
                data: $form.serialize(),
                success: function (response) {

                    var task = response.task;
                    $list.append('<li data-id="' + task.id + '"><input type="checkbox"  data-complete-task="' + task.id + '" ><label>' + task.name + '</label></li>');
                    $that.val("");
                    $that.removeClass('btn-danger').addClass('btn-success');
                },
                error: function () {
                    $that.removeClass('btn-success').addClass('btn-danger');
                }
            });
        });

        $('[data-complete-task]').on('click', function () {
            var id = $(this).data('complete-task');
            var $that = $(this);
            $.ajax({
                type: "PUT",
                data: {
                    '_token': '{{{ csrf_token() }}}'
                },
                url: '/tasks/' + id,
                success: function (response) {
                    if (response.taskState == true)
                        $that.closest('label').addClass('task-completed');
                    else
                        $that.closest('label').removeClass('task-completed');
                }
            });
        });
    });
</script>
@stop